### PR TITLE
Test mesh parallelization

### PR DESCRIPTION
**Pull request by emmetfrancis**
Initial alterations are just changing `d.MeshView.create()` to `d.create_meshview()` in `smart.mesh`. This PR should be tested with the [ghcr.io/scientificcomputing/fenics-gmsh:meshview_debug](http://ghcr.io/scientificcomputing/fenics-gmsh:meshview_debug)
 or
[ghcr.io/scientificcomputing/fenics:meshview_debug](http://ghcr.io/scientificcomputing/fenics:meshview_debug) docker images.

### CODE REVIEW

**Comment by emmetfrancis** [comment]
Initial testing was done just running the Jupyter notebook for example2-3d, leading to the following error:
`*** Error:   Unable to build sub-dofmap view.
*** Reason:  Re-ordering map not available. It may be been cleared by the user.
*** Where:   This error was encountered inside DofMapBuilder.cpp.
*** Process: 0`

The same error occurs when running a python script of the examples using mpi, for instance `mpiexec -np 2 python3 example2-3d.py`

**Comment by jorgensd** [comment]
Updated the `dokken/empty_mesh` branch to fix some bugs.
Runtime for Example2-3D:
Serial
```bash
real    2m43.099s
user    2m36.423s
sys     0m0.515s
```
2 processes
```bash
real    1m51.588s
user    3m29.911s
sys     0m0.787s
```
3 processes
```bash
real    1m29.597s
user    4m8.577s
sys     0m1.312s
```
4 processes
```bash
real    1m16.336s
user    4m38.111s
sys     0m1.937s
```
Note that at 4 processes we only have 15 000 cells and a total of ~25 000 dofs per process, which is a lot less than I would use for seeing good scaling (i would have at least 100 000 dofs per process).

8 processes
```bash
real    2m16.089s
user    15m35.485s
sys     0m6.492s
```

**Comment by jorgensd** [comment]
Example 1
Serial:
```bash
real    2m23.320s
user    2m15.638s
sys     0m1.239s
```
2 processes:
```bash
real    1m55.935s
user    3m36.124s
sys     0m2.358s
```
```
4 processes:
```bash
real    1m25.080s
user    5m9.166s
sys     0m4.105s
```
Note that the random generator makes it hard to verify the parallel solution in regression (as we take arrays of different lengths on each process from the same seed).

**Comment by jorgensd** [comment]
Example 2 (2D):
serial
```bash
real    0m38.031s
user    0m18.285s
sys     0m1.103s
```
2 processes:
```bash
real    0m45.647s
user    0m51.317s
sys     0m2.839s
```
4 processes:
```bash
real    0m45.610s
user    1m41.205s
sys     0m4.589s
```
Here we can check the error, and it is small across all runs.
We see a negative scaling as the problem is so small that communication cost more than the benefits of partitioning

**Comment by jorgensd** [comment]
Example 3:
Serial
```bash
real    27m16.674s
user    26m57.158s
sys     0m3.715s
```
2 processes:
```bash
real    17m10.697s
user    33m56.476s
sys     0m5.478s
```
4 processes:
```bash

real    10m32.169s
user    41m0.710s
sys     0m9.887s
```
8 processes:
```bash
real    6m14.272s
user    48m43.665s
sys     0m15.608s
```

**Comment by jorgensd** [comment]
Example 4:
Serial
```bash
real    1m26.538s
user    1m21.058s
sys     0m0.913s
```
2 processes
```bash
real    0m56.927s
user    1m43.129s
sys     0m0.745s
```
4 processes
```bash
real    0m45.394s
user    2m36.847s
sys     0m1.586s
```

8 processes
```bash

real    0m51.090s
user    5m55.921s
sys     0m3.454s
```
Note that on 8 processes the percentage error is slightly higher than the regression tolerance:
```bash
AssertionError: Failed regression test: Example 4 results deviate 0.023% from the previous numerical solution
```

**Comment by jorgensd** [comment]
Example 5:
Serial
```bash
real    1m8.439s
user    1m1.521s
sys     0m1.182s
```
2 proc:
```bash
real    1m23.122s
user    2m33.247s
sys     0m0.889s
```
Getting:
```bash
AssertionError: Failed regression test: Example 5 results deviate 0.296% from the previous numerical solution
```
@emmetfrancis  could you visually inspect a serial and parallel run and see if you can see any differences (or if this is just due to the solver)?

Important to note, we have an empty mesh on one process here:
```bash
 (model_assembly.py:304) 
 2023-07-13 12:34:30,106 CPU 0: smart.model_assembly - INFO - 
╒══════╤═══════════╤══════════════════╤═══════════════╤════════════════╤════════════╤══════════════════╤═════════════╤═══════════════╤═══════════════╕
│      │   mesh_id │   dimensionality │   num_species │   num_vertices │   num_dofs │   num_dofs_local │   num_cells │   cell_marker │ nvolume       │
╞══════╪═══════════╪══════════════════╪═══════════════╪════════════════╪════════════╪══════════════════╪═════════════╪═══════════════╪═══════════════╡
│ ERm  │        25 │                2 │             2 │            116 │        436 │              204 │         201 │            12 │ 8.34×10⁻¹ µm² │
├──────┼───────────┼──────────────────┼───────────────┼────────────────┼────────────┼──────────────────┼─────────────┼───────────────┼───────────────┤
│ ER   │        31 │                3 │             1 │            190 │        343 │              168 │         628 │             2 │ 5.27×10⁻² µm³ │
├──────┼───────────┼──────────────────┼───────────────┼────────────────┼────────────┼──────────────────┼─────────────┼───────────────┼───────────────┤
│ PM   │        38 │                2 │             0 │            289 │          0 │                0 │         512 │            10 │ 1.00×10⁰ µm²  │
├──────┼───────────┼──────────────────┼───────────────┼────────────────┼────────────┼──────────────────┼─────────────┼───────────────┼───────────────┤
│ Cyto │        44 │                3 │             2 │           2514 │       9576 │             4772 │       11554 │             1 │ 9.47×10⁻¹ µm³ │
╘══════╧═══════════╧══════════════════╧═══════════════╧════════════════╧════════════╧══════════════════╧═════════════╧═══════════════╧═══════════════╛
 (model_assembly.py:304) 
 2023-07-13 12:34:30,106 CPU 1: smart.model_assembly - INFO - 
╒══════╤═══════════╤══════════════════╤═══════════════╤════════════════╤════════════╤══════════════════╤═════════════╤═══════════════╤═══════════════╕
│      │   mesh_id │   dimensionality │   num_species │   num_vertices │   num_dofs │   num_dofs_local │   num_cells │   cell_marker │ nvolume       │
╞══════╪═══════════╪══════════════════╪═══════════════╪════════════════╪════════════╪══════════════════╪═════════════╪═══════════════╪═══════════════╡
│ ERm  │        25 │                2 │             2 │            126 │        436 │              232 │         226 │            12 │ 8.34×10⁻¹ µm² │
├──────┼───────────┼──────────────────┼───────────────┼────────────────┼────────────┼──────────────────┼─────────────┼───────────────┼───────────────┤
│ ER   │        31 │                3 │             1 │            202 │        343 │              175 │         668 │             2 │ 5.27×10⁻² µm³ │
├──────┼───────────┼──────────────────┼───────────────┼────────────────┼────────────┼──────────────────┼─────────────┼───────────────┼───────────────┤
│ PM   │        38 │                2 │             0 │              0 │          0 │                0 │           0 │            10 │ 1.00×10⁰ µm²  │
├──────┼───────────┼──────────────────┼───────────────┼────────────────┼────────────┼──────────────────┼─────────────┼───────────────┼───────────────┤
│ Cyto │        44 │                3 │             2 │           2539 │       9576 │             4804 │       11726 │             1 │ 9.47×10⁻¹ µm³ │
╘══════╧═══════════╧══════════════════╧═══════════════╧════════════════╧════════════╧══════════════════╧═════════════╧═══════════════╧═══════════════╛
```
4 processes:
```bash
real    1m25.804s
user    5m16.501s
sys     0m1.723s
```
Also regression error:
```bash
AssertionError: Failed regression test: Example 5 results deviate 0.259% from the previous numerical solution
```
These issue might be due to the fact that we are using an iterative solver with ~1e-5 tolerance.

**Comment by emmetfrancis** [comment]
@jorgensd @finsberg Upon preliminary testing, the new fixes seem to be working for parallelization in SMART! What do you think of merging this into the new branch I created for updating compatibility to the new FEniCS release, new-meshview?

**Review by jorgensd — APPROVED** [review]

**Pull request merged**
