### PR TITLE
Use jupyterbook and github pages instead of pure sphinx and readthedocs

### PR DESCRIPTION
**Pull request by finsberg**
Addressing https://github.com/justinlaughlin/stubs/issues/52

In this PR I am using [jupyter-book](https://jupyterbook.org/en/stable/intro.html) to create the documentation, and setting up a GitHub action that will host the pages on GitHub pages, i.e at https://justinlaughlin.github.io/stubs. 
I also converted most of the restructured text files to markdown, since jupyterbook support this through [`myst`](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html). Jupyter book also has a special directive for writing equations which you case see [here](https://jupyterbook.org/en/stable/content/math.html) and that I utilised in on of the new markdown files.  Note that to convert the `.rst` files to markdown I used [`pandoc`](https://pandoc.org/index.html)

The api reference is still in restructured text (in order for it to work with the autosummary and automodule directives in sphinx). Note that these extensions that you usually add to your `conf.py` is now added in the `sphinx.config` block inside the `_config.yml`.

I made some adjustments to  example1. I made it into a single file and then converted it to a jupyter notebook then I also included in the documentation. I converted the python file to a notebook using [jupytext](https://jupytext.readthedocs.io)

### CODE REVIEW

**Comment by jorgensd** [comment]
@justinlaughlin, @emmetfrancis I have now updated the config class to be type-set, and made such that users cannot send in undefined options to `config.Config`. 

The API of the class has not changed. 
Snapshot of how the docs look like below:
image
You can also access the config parameters without using a dictionary, i.e.
`config.loglevel.FFC` and `config.loglevel["FFC"]` gives the same return value.

**Comment by jorgensd** [comment]
@justinlaughlin  can we go ahead with this?

**Review by justinlaughlin — APPROVED** [review]
This looks really good, I'm learning a lot; thank you. Feel free to approve a MR without me if I'm holding things up.

**Comment by justinlaughlin** [comment]
> @justinlaughlin can we go ahead with this?

Of course - feel free to merge into dev without my approval if I am taking too long. I turned off a few config settings, e.g. "Preassemble linear system" was an experimental idea I had to save some assembly time on mostly linear systems. The code is pretty nascent and probably should default to false even if it gets developed further (I believe it will always increase memory usage and I couldn't get it efficient enough to be worth it).

**Pull request merged**
