### PR TITLE
Add 3D version of Example 2

### LINKED ISSUE #119: [JOSS Review] Reproducibility and functionality
Dear authors,

Generally speaking, the software runs as described in the documentation. However, there are very minor comments in this regard:

* The software claims to be high-performance, but no performance test is reported. Having a small test on example 3 (as the relevant example on parallelization) can be nice in this regard.
* Is there any way to reproduce Figure 1 of the paper? Example 2 performs the simulation on the mentioned model on a simple geometry.

P.S. This issue is related to https://github.com/openjournals/joss-reviews/issues/5580

### PR DESCRIPTION
**Pull request by emmetfrancis**
Add code for 3D version of Example 2, whose results are shown in Fig 1 of the JOSS paper. The folder includes an .xml file of the realistic dendritic spine geometry used for this simulation.

### CODE REVIEW

**Comment by emmetfrancis** [comment]
@jorgensd @finsberg Please let me know if you have any issues running this code, the output should roughly match what is shown in Fig 1 of the JOSS manuscript, and so it should address one of the concerns listed in the linked issue.

**Review by jorgensd — APPROVED** [review]
I made some fixes to the code (made sure that the web page builds all examples locally).
A thing we should keep in mind is that now with auto-clipping on, you get errors if the clip removes all cells, I think we might need to add a boolean input argument enabling clipping

**Review by finsberg — APPROVED** [review]

**Comment by emmetfrancis** [comment]
> I made some fixes to the code (made sure that the web page builds all examples locally). A thing we should keep in mind is that now with auto-clipping on, you get errors if the clip removes all cells, I think we might need to add a boolean input argument enabling clipping

I added in a boolean input as you suggested; currently just have the function catch the error and suggest changing to clip_logic=False if there is an error in rendering the clipped version; feel free to suggest any changes to this, thanks!

**Comment by emmetfrancis** [comment]
Extra note: This only solves one half of the linked issue; we should still respond to the following in some way:
> The software claims to be high-performance, but no performance test is reported. Having a small test on example 3 (as the relevant example on parallelization) can be nice in this regard.

**Comment by jorgensd** [comment]
Example 2 is missing a figure:
```bash
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[14], line 5
      3 ax = plt.subplot(2, 2, i+1)
      4 meshimg_file = meshimg_folder / f"ellipse_mesh_AR{aspect_ratios[i]}.png"
----> 5 img_cur = mpimg.imread(meshimg_file)
      6 plt.imshow(img_cur)
      7 plt.axis('off')

File /usr/lib/python3/dist-packages/matplotlib/image.py:1560, in imread(fname, format)
   1558                 response = io.BytesIO(response.read())
   1559             return imread(response, format=ext)
-> 1560 with img_open(fname) as image:
   1561     return (_pil_png_to_float_array(image)
   1562             if isinstance(image, PIL.PngImagePlugin.PngImageFile) else
   1563             pil_to_array(image))

File /usr/lib/python3/dist-packages/PIL/ImageFile.py:100, in ImageFile.__init__(self, fp, filename)
     96 self.decodermaxblock = MAXBLOCK
     98 if isPath(fp):
     99     # filename
--> 100     self.fp = open(fp, "rb")
    101     self.filename = fp
    102     self._exclusive_fp = True

FileNotFoundError: [Errno 2] No such file or directory: 'mesh_images/ellipse_mesh_AR1.png
```
image

**Pull request merged**
