### PR TITLE
Add image including pyvista and panel for plotting with jupyterlab

### LINKED ISSUE #118: [JOSS Review] Installation
Dear authors,

The software installation routine is straightforward, and there is no special issue with it. However, I found the package a bit difficult to get started with, especially for a normal user. If the package is supposed to be used by advanced users only (which I think is not), it should be explicitly mentioned. 

* After the installation using the docker approach, how is the user supposed to work with the examples? I think there is no way in the current setup. Jupyter is not installed in the docker image, and there is no port forwarding on the docker run command. I would say a non-advanced user can never find out how to do that, so it can be beneficial to guide the users on how to run the example codes and see how the library works in action. I did it by running `jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root` inside the container (after forwarding the port in the docker execution command), in which the inline PyVista visualization didn't still work (which is because PyVista is not installed inside the container). 
* As a follow-up to the above point, it can be nice if the user can have access to the example codes in separate files without the Jupyter notebooks, similar to example 3. These codes (accompanied by some documentation on how to run them) can show a normal user how to use the package after the installation.

P.S. This issue is related to https://github.com/openjournals/joss-reviews/issues/5580

### PR DESCRIPTION
**Pull request by jorgensd**
Resolves https://github.com/RangamaniLabUCSD/smart/issues/118

Note that we currently cannot install pyvista on ARM architecture, as it does not have binary wheels for linux: https://gitlab.kitware.com/vtk/vtk/-/issues/18772.

Building VTK from scratch in an emulator takes a very long time, 
```docker
RUN apt-get install -y build-essential mesa-common-dev mesa-utils freeglut3-dev ninja-build cmake
RUN CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_NUM_PROCESSES} \
    cmake -GNinja -B build-dir-vtk \
    -DCMAKE_BUILD_TYPE=Release \
    -DVTK_BUILD_TESTING=OFF \
    -DVTK_BUILD_DOCUMENTATION=OFF \
    -DVTK_BUILD_EXAMPLES=OFF \
    -DVTK_DATA_EXCLUDE_FROM_ALL:BOOL=ON \
    -DVTK_MODULE_ENABLE_VTK_PythonInterpreter:STRING=NO \
    -DVTK_MODULE_ENABLE_VTK_WebCore:STRING=YES \
    -DVTK_MODULE_ENABLE_VTK_WebGLExporter:STRING=YES \
    -DVTK_MODULE_ENABLE_VTK_WebPython:STRING=YES \
    -DVTK_WHEEL_BUILD=ON \
    -DVTK_PYTHON_VERSION=3 \
    -DVTK_WRAP_PYTHON=ON \
    -DVTK_OPENGL_HAS_EGL=False \
    vtk
RUN CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_NUM_PROCESSES} cmake --build build-dir-vtk
RUN CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_NUM_PROCESSES} cmake --install build-dir-vtk
```

```bash
#11 2562.4 [410/10078] Building CXX object Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkGenericDataSet.cxx.o
```
so I've only built 4 % of VTK in 42 minutes (which would time out on CI).

### CODE REVIEW

**Review by emmetfrancis — COMMENTED** [review]
Thanks for adding this, it looks great! Should we update the visualization module in this PR as well so that if pyvista is not installed, it will still run?

**Comment by emmetfrancis** [comment]
Also, is it worth included .py versions of all the examples (this was suggested in the issue) so users can run without Jupyter notebooks?

**Comment by jorgensd** [comment]
> Also, is it worth included .py versions of all the examples (this was suggested in the issue) so users can run without Jupyter notebooks?

I've added instructions on how convert the notebooks in to python files in the README. Im a bit reluctant to convert them and add them to the repo, as it increases the maintenance/syncronization on our end. We could add them when generating the docker image though. @finsberg  any thoughts?

**Comment by jorgensd** [comment]
> Thanks for adding this, it looks great! Should we update the visualization module in this PR as well so that if pyvista is not installed, it will still run?

Yes we should

**Comment by jorgensd** [comment]
I've now fixed both these issues @emmetfrancis

**Review by finsberg — APPROVED** [review]

**Comment by finsberg** [comment]
`pyvista` now also works for arm64. I uploaded a wheel for `vtk` here: https://github.com/finsberg/vtk-aarch64

**Review by emmetfrancis — APPROVED** [review]
Looks great to me, thanks for working on this!

**Pull request merged**
